function txt = gps_dc_update(obj, event_obj, gps_x, gps_y, gps_ts,...
                              gps_lat, gps_lon)
    ps = get(event_obj, 'Position');
    data_idx = find( (gps_x(:) == ps(1)) & (gps_y(:) == ps(2)));
    t = gps_ts(data_idx);
    txt = {['x: ',num2str(ps(1))],...
        ['y: ',num2str(ps(2))],...
        ['time: ', sprintf('%10.6f', t(1))],...
        ['lat: ', num2str(gps_lat(data_idx(1)))],...
        ['lon: ', num2str(gps_lon(data_idx(1)))]};
end
